# Generated by Django 5.1 on 2024-10-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
