# Generated by Django 5.1 on 2024-10-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0002_camion_ultima_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='latitud',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='camion',
            name='longitud',
            field=models.FloatField(null=True),
        ),
    ]
