# Generated by Django 5.1 on 2024-10-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0005_alter_camion_latitud_alter_camion_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='latitud',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='camion',
            name='longitud',
            field=models.FloatField(null=True),
        ),
    ]
