# Generated by Django 5.1 on 2024-10-14 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0006_alter_camion_latitud_alter_camion_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camion',
            name='usuario',
        ),
    ]
