# Generated by Django 5.1 on 2024-11-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0009_remove_camion_chofer_asignado_alter_camion_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionchofer',
            name='en_viaje',
            field=models.BooleanField(default=False),
        ),
    ]
