# Generated by Django 5.1 on 2024-11-18 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0010_asignacionchofer_en_viaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('ruta', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='En curso', max_length=50)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='camiones.camion')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
