# Generated by Django 4.1.5 on 2024-12-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0011_historialviaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialviaje',
            name='latitud_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialviaje',
            name='longitud_final',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
