# Generated by Django 4.1.5 on 2024-12-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0012_historialviaje_latitud_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialviaje',
            name='latitud_inicial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialviaje',
            name='longitud_inicial',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
