# Generated by Django 4.1.5 on 2024-12-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0013_historialviaje_latitud_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialviaje',
            name='duracion_total',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
