# Generated by Django 5.1 on 2024-12-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0014_historialviaje_duracion_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
