# Generated by Django 5.1 on 2024-12-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0015_chofer_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='api_key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
