# Generated by Django 5.1 on 2024-12-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0016_chofer_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajePredefinido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('cuerpo', models.TextField()),
            ],
        ),
    ]
