# Generated by Django 4.1.5 on 2024-12-13 23:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0017_mensajepredefinido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_viaje', models.DateTimeField(default=django.utils.timezone.now)),
                ('origen', models.CharField(max_length=255)),
                ('patente', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en curso', 'En Curso'), ('finalizado', 'Finalizado')], default='pendiente', max_length=50)),
                ('transporte', models.CharField(max_length=255)),
                ('producto', models.CharField(max_length=255)),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='viajes/')),
                ('latitud_inicial', models.FloatField(blank=True, null=True)),
                ('longitud_inicial', models.FloatField(blank=True, null=True)),
                ('latitud_final', models.FloatField(blank=True, null=True)),
                ('longitud_final', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
