# Generated by Django 5.1 on 2024-12-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0019_estado_alter_viaje_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camion',
            name='choferes_asignados',
        ),
        migrations.AddField(
            model_name='camion',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Asignado', 'Asignado')], default='Disponible', max_length=20),
        ),
    ]
